sudo: false
language: node_js
node_js:
  - '8'
  - '10'
install:
  - npm install
script:
  - npm run lint
  - npm run test
  - npm run travis
after_success:
  - npm i codecov && codecov
deploy:
  provider: releases
  file: webclipper.zip
  skip_cleanup: true
  on:
    repo: webclipper/web-clipper
    tags: true
